#abra o terminal e utilize: docker-compose up -d

version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_exceltodb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      
volumes:
  mysql_data: